version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - REDIS_URL=redis://redis:6379/0
      - SQLALCHEMY_DATABASE_URI=sqlite:////code/sql_app.db

  db:
    image: sqlite
    volumes:
      - ./sql_app.db:/code/sql_app.db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    command: celery -A app.services.celery_worker worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - web
    environment:
      - REDIS_URL=redis://redis:6379/0

volumes:
  redis_data: